#!/bin/bash
set -e

APPSTORAGE=/u01

## Install and configure a WLS server to export a remote attached LUN.

### Send stdout, stderr to /var/log/messages/
exec 1> >(logger -s -t $(basename $0)) 2>&1

### Storage setup, assume dev arrives as sdb
wget -O /usr/local/bin/iscsiattach.sh https://raw.githubusercontent.com/oracle/terraform-provider-oci/master/docs/examples/storage/nfs/userdata/iscsiattach.sh
chmod +x /usr/local/bin/iscsiattach.sh
/usr/local/bin/iscsiattach.sh

#mkfs.xfs /dev/sdb
#mkdir $APPSTORAGE
#mount -t xfs /dev/sdb $APPSTORAGE
sdb_uuid=`blkid /dev/sdb -s UUID -o value`
#echo "UUID=$sdb_uuid    $APPSTORAGE    xfs    defaults,noatime,_netdev,nofail" >> /etc/fstab

# Docker setup
yum -y install docker-engine git
docker-storage-config -f -s btrfs -d /dev/sdb
systemctl enable docker
yum -y install oracle-rdbms-server-12cR1-preinstall oracleasm-support

### Firewall
firewall-offline-cmd --zone=public --add-port=1521/tcp --add-port=5500/tcp

## YUM update
yum update -y

## Restart services
systemctl restart firewalld.service
systemctl restart docker
